name: tormentor
channels:
  - anaconda
  - bioconda
dependencies:
  - python
  - git
  - cmake
  - seqkit
  - viennarna
  - spades
  - pyyaml=3.12
  - prodigal
  - fastp
  - pip
  - infernal
  - pip:
    - -e .